GET http://localhost:8080/api/v1/avlist

###

GET http://localhost:8080/api/v1/avlist/1
###

POST http://localhost:8080/api/v1/avlist
Content-Type: application/json

{
  "product_name": "商品1",
  "product_point": "100",
  "product_image_id": "1"
}

###

PUT http://localhost:8080/api/v1/avlist/4
Content-Type: application/json

{
  "id": "4",
  "product_name": "商品4",
  "product_point": "200",
  "product_image_id": "6"
}

###

DELETE http://localhost:8080/api/v1/avlist/1