@baseUrl = http://localhost:8080/api/product
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIyNjRlODQxOC1hZDNhLTQxZjMtYTg3OS01N2RiMTMwNzAyNDgiLCJleHAiOjE2NzM0MzQ2Njd9.GWDUqbDv0t39tbY_CApz5pHVndF3xwnONEpczk_pJz4

### 商品表示
GET {{baseUrl}} HTTP/1.1
Authorization: {{token}}

### 商品追加
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "name": "syohin2",
  "usePoint": "200"
}

###　商品更新
PUT {{baseUrl}}/1 HTTP/1.1
Content-Type: application/json

{
  "name": "syouhin99",
  "usePoint": "999"
}

### 商品削除
DELETE {{baseUrl}}/2 HTTP/1.1