GET http://localhost:8080/api/users HTTP/1.1

###
GET http://localhost:8080/login HTTP/1.1

###
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "84d6c0f9-c772-4b6a-ba6b-683f86710a6a"
}