spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: true

  datasource:
    url: jdbc:mysql://db:3306/db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver