server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: true
  datasource:
    url: jdbc:mysql://db:3306/db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
