version: "3.9"

services:
  db:
    image: mysql:8.0.19
    container_name: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5555:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root

  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace
    build:
      context: ./docker/workspace
      args:
        USERNAME: ${USERNAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    depends_on:
      - db
    volumes:
      - ../:/home/${USERNAME:-vscode}/workspace:cached
    ports:
      - 8080:80
