### ポイント更新
PUT http://localhost:8080/api/property/point/id HTTP/1.1
content-type: application/json

{
  "havePoint": "500"
}

### 株購入
PUT http://localhost:8080/api/property/point/id HTTP/1.1
content-type: application/json

{
  "havePoint": "500",
  "haveStock": "500"
}